/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class natif_natifUpd */

#ifndef _Included_natif_natifUpd
#define _Included_natif_natifUpd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     natif_natifUpd
 * Method:    get_shared_bytes
 * Signature: (Ljava/lang/String;)Ljava/nio/ByteBuffer;

JNIEXPORT jobject JNICALL Java_natif_natifUpd_get_1shared_1bytes
  (JNIEnv *, jclass, jstring);
*/
/*
 * Class:     natif_natifUpd
 * Method:    mapUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_natif_natifUpd_mapUp
  (JNIEnv *, jclass, int i);

#ifdef __cplusplus
}
#endif
#endif